apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: retail-store
  namespace: argocd
spec:
  description: Retail Store microservices on EKS Auto Mode
  sourceRepos:
    - https://github.com/Honeyshah624/retail-store-gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: retail-store
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
