apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: retail-store
  namespace: argocd
spec:
  description: Retail Store multi-environment deployment on EKS Auto Mode

  sourceRepos:
    - https://github.com/Honeyshah624/retail-store-kustomize-argocd.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: retail-store-dev

    - server: https://kubernetes.default.svc
      namespace: retail-store-staging

    - server: https://kubernetes.default.svc
      namespace: retail-store-prod

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"