apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-store-dev

resources:
  - ../../../base/carts

images:
  - name: public.ecr.aws/aws-containers/retail-store-sample-cart
    newName: 454143665149.dkr.ecr.ap-south-1.amazonaws.com/retail-store/carts
    newTag: 1.6.2

replicas:
  - name: carts
    count: 1

labels:
  - pairs:
      environment: dev
    includeSelectors: false