apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-store-prod

resources:
  - ../../../base/orders

images:
  - name: public.ecr.aws/aws-containers/retail-store-sample-orders
    newName: public.ecr.aws/aws-containers/retail-store-sample-orders
    newTag: 1.6.2

replicas:
  - name: orders
    count: 3

labels:
  - pairs:
      environment: prod
    includeSelectors: false