apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: retail-store
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: in-memory
  RETAIL_ORDERS_MESSAGING_PROVIDER: in-memory
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: retail-store
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orders
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels: &id001
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: retail-store
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: orders
        image: public.ecr.aws/aws-containers/retail-store-sample-orders:1.6.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: orders
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          periodSeconds: 5
          failureThreshold: 30
