apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-store
resources:
  - ../../../base/catalog
images:
  - name: public.ecr.aws/aws-containers/retail-store-sample-catalog
    newTag: 1.6.2
replicas:
  - name: catalog
    count: 1
