apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-store-staging

resources:
  - ../../../base/catalog

images:
  - name: public.ecr.aws/aws-containers/retail-store-sample-catalog
    newName: 454143665149.dkr.ecr.ap-south-1.amazonaws.com/retail-store/catalog
    newTag: 1.6.2

replicas:
  - name: catalog
    count: 2

labels:
  - pairs:
      environment: staging
    includeSelectors: false